# YAML configuration file
working_dir_path: 6X18_PR_ext        # Folder to write i/o files of the workflow steps
can_write_console_log: False      # Verbose writing of log information
restart: True                     # Skip steps already performed

complex_structure: ./selected sample/6X18_PR_-_minimized.pdb
selected_chains: [P, ]


step_pdb2gmx:
  paths:
    output_gro_path: pdb2gmx.gro
    output_top_zip_path: pdb2gmx_top.zip
  properties:
    force_field: amber99sb-ildn # des-amber, amber99sb-ildn, charmm27
    water_type: tip3p
    ignh: True
    maxwarn: 1

step_editconf:
  paths:
    input_gro_path: dependency/step_pdb2gmx/output_gro_path
    output_gro_path: editconf.gro
  properties:
    box_type: triclinic       # triclinic, cubic, dodecahedron, octahedron
    distance_to_molecule: 0.7 # nm
    center_molecule: True

step_solvate:
  paths:
    input_solute_gro_path: dependency/step_editconf/output_gro_path
    output_gro_path: solvate.gro
    input_top_zip_path: dependency/step_pdb2gmx/output_top_zip_path
    output_top_zip_path: solvate_top.zip

step_grompp_genion:
  paths:
    input_gro_path: dependency/step_solvate/output_gro_path
    input_top_zip_path: dependency/step_solvate/output_top_zip_path
    output_tpr_path: gppion.tpr
  properties:
    maxwarn: 1
    simulation_type: minimization

step_genion:
  paths:
    input_tpr_path: dependency/step_grompp_genion/output_tpr_path
    output_gro_path: genion.gro
    input_top_zip_path: dependency/step_solvate/output_top_zip_path
    output_top_zip_path: genion_top.zip
  properties:
    neutral: True
    concentration: 0.05


free_energy_parameters:
  properties:
    mdp:
      free-energy: 'yes'
      delta_lambda: 0
      calc-lambda-neighbors: -1   # 1: only immediate neighboring windows; -1: differences in Hamiltonians between all states
      couple-lambda0: 'vdw-q'     #
      couple-lambda1: 'none'      #
      couple-intramol: 'no'      # Intramolecular terms are not turned off. Usually what you want so you don't have to run it again in vacuum.
      vdw-lambdas:         '0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.05 0.10 0.15 0.20 0.25 0.30 0.35 0.40 0.45 0.50 0.55 0.60 0.65 0.70 0.75 0.80 0.85 0.90 1.00' #'0.00000  0.11850  0.18978  0.24741  0.32525  0.45630  0.60  0.7  0.8   1.00000  1.00000  1.00000  1.00000  1.00000'
      coul-lambdas:        '0.00 0.05 0.10 0.15 0.20 0.25 0.30 0.35 0.40 0.45 0.50 0.55 0.60 0.65 0.70 0.80 0.90 1.00 1.00 1.00 1.00 1.00 1.00 1.00 1.00 1.00 1.00 1.00 1.00 1.00 1.00 1.00 1.00 1.00 1.00 1.00'
#      bonded-lambdas:      '0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0'
#      restraint-lambdas:   '0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0'
#      mass-lambdas:        '0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0'
#      temperature-lambdas: '0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0'
      nstdhdl: 100

      sc-alpha: 0.5
      sc-coul: 'no'       # Don't use soft-core for electrostatics.
      sc-power: 1
      sc-sigma: 0.3

      constraints: 'h-bonds'
      constraint-algorithm: 'lincs'
      lincs-order: 6

      coulombtype: 'PME'
      rcoulomb: '1.2'
      fourierspacing: 0.125

      vdwtype: 'Cut-off'
      vdw-modifier: 'Potential-shift' # FF-dependent
      rvdw-switch: '0.0'              # FF-dependent
      rvdw: '1.0'                     # FF-dependent
      DispCorr: 'EnerPres'            # FF-dependent


step_grompp_min:
  paths:
    output_tpr_path: gppmin.tpr
  properties:
    mdp:
      nsteps: 5000
      emtol: 50
    simulation_type: minimization

step_mdrun_min:
  paths:
    input_tpr_path: dependency/step_grompp_min/output_tpr_path
    output_trr_path: min.trr
    output_gro_path: min.gro
    output_edr_path: min.edr
    output_log_path: min.log

step_energy_min:
  paths:
    input_energy_path: dependency/step_mdrun_min/output_edr_path
    output_xvg_path: min_ene.xvg


step_grompp_nvt:
  paths:
    input_gro_path: dependency/step_mdrun_min/output_gro_path
    output_tpr_path: gppnvt.tpr
  properties:
    mdp:
      integrator: 'sd'
      nsteps: 5000
    simulation_type: nvt
    maxwarn: 1

step_mdrun_nvt:
  paths:
    input_tpr_path: dependency/step_grompp_nvt/output_tpr_path
    output_trr_path: nvt.trr
    output_gro_path: nvt.gro
    output_edr_path: nvt.edr
    output_log_path: nvt.log
    output_cpt_path: nvt.cpt

step_energy_nvt:
  paths:
    input_energy_path: dependency/step_mdrun_nvt/output_edr_path
    output_xvg_path: nvt_temp.xvg


step_grompp_npt:
  paths:
    input_gro_path: dependency/step_mdrun_nvt/output_gro_path
    input_top_zip_path: dependency/step_genion/output_top_zip_path
    output_tpr_path: gppnpt.tpr
    input_cpt_path: dependency/step_mdrun_nvt/output_cpt_path
  properties:
    mdp:
      integrator: 'sd'
      nsteps: 15000
      pcoupl: 'Parrinello-Rahman'
      tau-p: 1.0
      compressibility: '4.5e-05'
      ref-p: 1.0
      continuation: 'yes'
    simulation_type: npt
    maxwarn: 1

step_mdrun_npt:
  paths:
    input_tpr_path: dependency/step_grompp_npt/output_tpr_path
    output_trr_path: npt.trr
    output_gro_path: npt.gro
    output_edr_path: npt.edr
    output_log_path: npt.log
    output_cpt_path: npt.cpt

step_energy_npt:
  paths:
    input_energy_path: dependency/step_mdrun_npt/output_edr_path
    output_xvg_path: npt_den_press.xvg


step_grompp_md:
  paths:
    input_gro_path: dependency/step_mdrun_npt/output_gro_path
    input_top_zip_path: dependency/step_genion/output_top_zip_path
    output_tpr_path: gppmd.tpr
    input_cpt_path: dependency/step_mdrun_npt/output_cpt_path
  properties:
    mdp:
      nsteps: 100000
      integrator: 'sd'
      tc-grps: 'system'
      tau-t: 1.0
      ref-t: 298
      pcoupl: 'Parrinello-Rahman'
      tau-p: 2.0
      compressibility: '4.5e-05'
      ref-p: 1.0
      continuation: 'yes'
      nstenergy: 500
    simulation_type: free
    maxwarn: 1

step_mdrun_md:
  paths:
    input_tpr_path: dependency/step_grompp_md/output_tpr_path
    output_trr_path: md.trr
    output_gro_path: md.gro
    output_edr_path: md.edr
    output_log_path: md.log
    output_cpt_path: md.cpt
    output_dhdl_path: dhdl.xvg

step_energy_md:
  paths:
    input_energy_path: dependency/step_mdrun_md/output_edr_path
    output_xvg_path: md_den_press.xvg
